# Generated by Django 2.1.8 on 2019-05-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_auto_20190505_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='이름'),
        ),
    ]
