# Generated by Django 2.1.8 on 2019-05-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_auto_20190505_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='path',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='단축 경로'),
        ),
    ]
