# Generated by Django 2.1.8 on 2019-05-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_link_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='path',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='단축 경로'),
        ),
    ]
