# Generated by Django 2.1.8 on 2019-05-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0007_auto_20190505_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='path',
            field=models.CharField(max_length=50, verbose_name='단축 경로'),
        ),
    ]
